server:
  port: 80
  max-http-header-size: 10240

guns:
  spring-session-open: false        #是否开启spring session,如果是多机环境需要开启(true/false)
  session-invalidate-time: 1800     #session失效时间(只在单机环境下生效，多机环境在SpringSessionConfig类中配置) 单位：秒
  session-validation-interval: 900  #多久检测一次失效的session(只在单机环境下生效) 单位：秒

beetl:
  resource-auto-check: true         #热加载beetl模板，开发时候用

spring:
  profiles:
    active: @spring.active@
  mvc:
    view:
      prefix: /pages
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
#redis集群
  redis:
    host: 127.0.0.1
    port: 16379
    timeout: 20000
mybatis-plus:
  typeAliasesPackage: cn.stylefeng.guns.modular.system.model
  mapper-locations:
    - classpath*:cn/stylefeng/guns/**/mapping/*.xml
log:
  path: _app_logs
#rocketMQ配置
#rocketmq:
#  name-server: 127.0.0.1:9876
#  producer:
#    group: broker-a
#    sendMessageTimeout: 30000
rocketmq:
  consumer:
    # RocketMQ的请求地址
    namesrvAddr: 127.0.0.1:9876
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: broker-a
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: consumer.demo
  producer:
    #发送消息超时时间
    sendMsgTimeout: 10000
    #maxMessageSize最大消息限制
    maxMessageSize: 999999999
    #消息大小超出配置对消息压缩
    compressOver: 40000
  topic: submit
  tag: "*"
